force-app/main/default/objects/Annonce__c/Annonce__c.object-meta.xml
<CustomObject>
    <label>Annonce</label>
    <nameField>
        <label>Annonce</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Annonces</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Annonce__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Diffusée</fullName>
                <default>true</default>
                <label>Diffusée</label>
            </value>
            <value>
                <fullName>Prise en compte</fullName>
                <label>Affectée</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/VFC10VeilleLue.cls
/*
----------------------------------------------------------------------
-- - Name          : VFC10VeilleLue
-- - Author        : Bluetis
-- - Description   : Extension for VFP10VeilleLue
-- - Module        : CRM Ingerop
--
-- Maintenance History:
--
-- Date         Name  Version  Remarks  
-- -----------  ----  -------  ---------------------------------------
-- 30-NOV-2016   BLU    1.0      Initial version
----------------------------------------------------------------------
*/
public without sharing class VFC10VeilleLue {
  public Annonce__c veille {get;set;}
   public id annonceId {get;set;}

  public VFC10VeilleLue(ApexPages.StandardController controller) {
    System.debug('## VFC10VeilleLue.init START');
    annonceId = ApexPages.currentPage().getParameters().get('AnnonceId');
    veille = DAL.getVeilleById(annonceId);
    System.debug('## VFC10VeilleLue.init END');
  }
    
    @RemoteAction
    public static void recuperation(String veilleId) {
        try {
          /* MAJ de l'annonce */
            Annonce__c annonce = DAL.getVeilleById(veilleId);
            if(annonce != null){ 
                /*Recherche de veille ou création si destinataire absent*/
                List<Veille__c> listVeille = DAL.getVeilleByUserId(UserInfo.getUserId(), annonce.Id);
                
                if(listVeille.isEmpty()){
                  Veille__c v = new Veille__c();
                  v.Annonce__c = annonce.Id;
                  v.Destinataire__c = UserInfo.getUserId();
                  v.Statut__c = Label.AnnonceLuStatut;
                  insert v;
                }else{
                  listVeille[0].Statut__c = Label.AnnonceLuStatut;
                  update listVeille;
                }
            }                       
        } catch(Exception e) {
           System.debug('## ERREUR : '+ e.getMessage());
        }
    }
    }