force-app/main/default/objects/Annonce__c/Annonce__c.object-meta.xml
<CustomObject>
    <label>Annonce</label>
    <nameField>
        <label>Annonce</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Annonces</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Annonce__c/fields/Operation__c.field-meta.xml
<CustomField>
    <fullName>Operation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opération</label>
    <referenceTo>Operation__c</referenceTo>
    <relationshipName>Veilles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AnnonceOperations__c/AnnonceOperations__c.object-meta.xml
<CustomObject>
    <description>Objet de lien entre Annonce et Opération</description>
    <label>Annonce Opération</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Annonce Opération</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Annonces / Opérations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AnnonceOperations__c/fields/Annonce__c.field-meta.xml
<CustomField>
    <fullName>Annonce__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Annonce</label>
    <referenceTo>Annonce__c</referenceTo>
    <relationshipLabel>Annonces / Opérations</relationshipLabel>
    <relationshipName>Annonce_Operation_Account</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AnnonceOperations__c/fields/Compte__c.field-meta.xml
<CustomField>
    <fullName>Compte__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compte</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Annonces / Opérations</relationshipLabel>
    <relationshipName>Annonces_Operations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AnnonceOperations__c/fields/ID_Explore__c.field-meta.xml
<CustomField>
    <fullName>ID_Explore__c</fullName>
    <formula>Annonce__r.IdExplore__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ID Explore</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AnnonceOperations__c/fields/Lien_Explore__c.field-meta.xml
<CustomField>
    <fullName>Lien_Explore__c</fullName>
    <formula>HYPERLINK(&quot;https://extranet.explore.fr/DotNet/AffichageMarchePublic.aspx?projet=&quot; &amp;  TEXT(Annonce__r.IdExploreSimplifie__c), &quot;Lien Explore&quot;)</formula>
    <label>Lien Explore</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AnnonceOperations__c/fields/Link__c.field-meta.xml
<CustomField>
    <fullName>Link__c</fullName>
    <formula>&quot;/lightning/r/AnnonceOperation__c/&quot;+Id+&quot;/view&quot;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Link</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AnnonceOperations__c/fields/Operation__c.field-meta.xml
<CustomField>
    <fullName>Operation__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opération</label>
    <referenceTo>Operation__c</referenceTo>
    <relationshipLabel>Annonces / Opérations</relationshipLabel>
    <relationshipName>Annonce_Operation_Account</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AnnonceOperations__c/fields/URL_Explore__c.field-meta.xml
<CustomField>
    <fullName>URL_Explore__c</fullName>
    <formula>&quot;https://extranet.explore.fr/DotNet/AffichageMarchePublic.aspx?projet=&quot; &amp; TEXT(Annonce__r.IdExploreSimplifie__c)</formula>
    <label>URL Explore</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Operation__c/Operation__c.object-meta.xml
<CustomObject>
    <label>Opération</label>
    <nameField>
        <label>Nom de l&apos;opération</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opérations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Operation__c/fields/Compte__c.field-meta.xml
<CustomField>
    <fullName>Compte__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Compte</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opérations</relationshipLabel>
    <relationshipName>Projets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Operation__c/fields/Departement__c.field-meta.xml
<CustomField>
    <fullName>Departement__c</fullName>
    <label>Département</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Pays__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1	Ain</fullName>
            </value>
            <value>
                <fullName>2	Aisne</fullName>
            </value>
            <value>
                <fullName>3	Allier</fullName>
            </value>
            <value>
                <fullName>4	Alpes de Haute Provence</fullName>
            </value>
            <value>
                <fullName>5	Hautes-Alpes</fullName>
            </value>
            <value>
                <fullName>6	Alpes-Maritimes</fullName>
            </value>
            <value>
                <fullName>7	Ardèche</fullName>
            </value>
            <value>
                <fullName>8	Ardennes</fullName>
            </value>
            <value>
                <fullName>9	Ariège</fullName>
            </value>
            <value>
                <fullName>10	Aube</fullName>
            </value>
            <value>
                <fullName>11	Aude</fullName>
            </value>
            <value>
                <fullName>12	Aveyron</fullName>
            </value>
            <value>
                <fullName>13	Bouches-du-Rhône</fullName>
            </value>
            <value>
                <fullName>14	Calvados</fullName>
            </value>
            <value>
                <fullName>15	Cantal</fullName>
            </value>
            <value>
                <fullName>16	Charente</fullName>
            </value>
            <value>
                <fullName>17	Charente-Maritime</fullName>
            </value>
            <value>
                <fullName>18	Cher</fullName>
            </value>
            <value>
                <fullName>19	Corrèze</fullName>
            </value>
            <value>
                <fullName>21	Côte d&apos;Or</fullName>
            </value>
            <value>
                <fullName>22	Côtes d&apos;Armor</fullName>
            </value>
            <value>
                <fullName>23	Creuse</fullName>
            </value>
            <value>
                <fullName>24	Dordogne</fullName>
            </value>
            <value>
                <fullName>25	Doubs</fullName>
            </value>
            <value>
                <fullName>26	Drôme</fullName>
            </value>
            <value>
                <fullName>27	Eure</fullName>
            </value>
            <value>
                <fullName>28	Eure-et-Loir</fullName>
            </value>
            <value>
                <fullName>29	Finistère</fullName>
            </value>
            <value>
                <fullName>2A	Corse du Sud</fullName>
            </value>
            <value>
                <fullName>2B	Haute Corse</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Operation__c/fields/estDansMonDepartement__c.field-meta.xml
<CustomField>
    <fullName>estDansMonDepartement__c</fullName>
    <description>Champ masqué, vérifie si le département de l&apos;opération est le même que celui de l&apos;utilisateur</description>
    <formula>OR((TEXT( Departement_du_Pole__c )==TEXT( $User.Departement_du_Pole__c )),ISPICKVAL($User.Departement_du_Pole__c,&quot;&quot;))</formula>
    <label>estDansMonDepartement</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Operation__c/fields/estDansMonPole__c.field-meta.xml
<CustomField>
    <fullName>estDansMonPole__c</fullName>
    <description>Champ masqué. Vérifie si le Pôle de l&apos;opération est le même que celui de l&apos;utilisateur</description>
    <formula>OR((TEXT(Pole__c) == TEXT( $User.Pole__c)),ISPICKVAL($User.Pole__c,&quot;&quot;))</formula>
    <label>estDansMonPole</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Operation__c/fields/estDansMonService__c.field-meta.xml
<CustomField>
    <fullName>estDansMonService__c</fullName>
    <description>Champ masqué, vérifie si le service de l&apos;opération est le même que celui de l&apos;utilisateur</description>
    <formula>OR((TEXT( Service__c ) == TEXT( $User.Service__c )),ISPICKVAL($User.Service__c,&quot;&quot;))</formula>
    <label>estDansMonService</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Operation__c/fields/estDansMonUFO__c.field-meta.xml
<CustomField>
    <fullName>estDansMonUFO__c</fullName>
    <description>Champ masqué utilisé pour les rapports uniquement. Vérifie si l&apos;UFO de l&apos;utilisateur est la même que celle de l&apos;opération</description>
    <formula>OR(( TEXT(UFO__c) ==  TEXT($User.UFO__c)),  ISPICKVAL($User.UFO__c,&quot;&quot;) )</formula>
    <label>estDansMonUFO</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Operation__c/fields/link__c.field-meta.xml
<CustomField>
    <fullName>link__c</fullName>
    <formula>&quot;/lightning/r/Operation__c/&quot;+Id+&quot;/view&quot;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>link</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Operation__c/fields/Nom_du_r_f_rent__c.field-meta.xml
<CustomField>
    <fullName>Nom_du_r_f_rent__c</fullName>
    <formula>Owner:User.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Nom du référent</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Operation__c/fields/Nombre_d_offres__c.field-meta.xml
<CustomField>
    <fullName>Nombre_d_offres__c</fullName>
    <description>Nombre d&apos;Offres issues des Équipes/Candidatures de l&apos;Opération</description>
    <label>Nombre d&apos;offres</label>
    <summarizedField>Equipe_Candidature__c.Nombre_d_offres__c</summarizedField>
    <summaryForeignKey>Equipe_Candidature__c.Operation__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Operation__c/fields/UFO__c.field-meta.xml
<CustomField>
    <fullName>UFO__c</fullName>
    <label>UFO</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ALPES CENTRE EST</fullName>
            </value>
            <value>
                <fullName>BATIMENT &amp; EQUIPEMENTS</fullName>
            </value>
            <value>
                <fullName>BUSINESS INGEROP CONTRACTING</fullName>
            </value>
            <value>
                <fullName>GEOS</fullName>
            </value>
            <value>
                <fullName>GRAND OUEST</fullName>
            </value>
            <value>
                <fullName>INFRASTRUCTURES, VILLE &amp; TRANSPORTS</fullName>
            </value>
            <value>
                <fullName>INTERNATIONAL</fullName>
            </value>
            <value>
                <fullName>MEDITERRANEE</fullName>
            </value>
            <value>
                <fullName>NORD-EST</fullName>
            </value>
            <value>
                <fullName>RENDEL PLUS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/LCCTRL_AnnonceRelatedOperations.cls
public with sharing class LCCTRL_AnnonceRelatedOperations {
    
    @AuraEnabled
    public static ObjectWrapper fetchData(String infoJSON) {
        ComponentInfo info = (ComponentInfo)JSON.deserialize(infoJSON, ComponentInfo.class);
        
        String parentField = info.parentField;
        Id parentRecordId = info.parentRecordId;
        
        //System.debug('# fetchData / parentField : ' + parentField);
        //System.debug('# fetchData / parentRecordId : ' + parentRecordId);
        
        if (String.isNotEmpty(info.objectType)) {
            String countQuery = getCountQueryString(info);
            String queryObjects = getObjectQueryString(info);
            
            //System.debug('# fetchData / countQuery : ' + countQuery);
        	//System.debug('# fetchData / queryObjects : ' + queryObjects);
            
            return new ObjectWrapper(
                info.recordToDisplay,
                info.pageNumber,
                Database.countQuery(countQuery),
                Database.query(queryObjects)
            );
        } else {
            return new ObjectWrapper();
        }
    }
    
    private static String getCountQueryString(ComponentInfo info) {
        String objectType = String.escapeSingleQuotes(info.objectType);
        String parentField = info.parentField;
        Id parentRecordId = info.parentRecordId;
        
        //System.debug('# getObjectQueryString / objectType : ' + objectType);
        //System.debug('# getCountQueryString / parentField : ' + parentField);
        //System.debug('# getCountQueryString / parentRecordId : ' + parentRecordId);
        
        String countQuery = 'SELECT count() FROM ';
        countQuery += objectType;
        
        if (String.isNotEmpty(parentField) && parentRecordId != null) {
            parentField = String.escapeSingleQuotes(parentField);
            countQuery += ' WHERE ' + parentField + ' = : parentRecordId';
        }
        
        return countQuery;
    }
    
    private static String getObjectQueryString(ComponentInfo info) {
        String objectType = String.escapeSingleQuotes(info.objectType);
        String parentField = info.parentField;
        Id parentRecordId = info.parentRecordId;
        
        System.debug('# getObjectQueryString / objectType : ' + objectType);
        System.debug('# getObjectQueryString / parentField : ' + parentField);
        System.debug('# getObjectQueryString / parentRecordId : ' + parentRecordId);
        
        String queryObjects = 'SELECT Id, Name, link__c, ID_Explore__c, Lien_Explore__c, URL_Explore__c, Operation__c, Operation__r.Name, CreatedDate, Annonce__c, Operation__r.UFO__c, Operation__r.Owner.Name, Operation__r.Compte__c, Operation__r.Compte__r.Name  FROM ';
        queryObjects += objectType;
        
        if (String.isNotEmpty(parentField) && parentRecordId != null) {
            parentField = String.escapeSingleQuotes(parentField);
            queryObjects += ' WHERE ' + parentField +' = : parentRecordId';
        } else {
            queryObjects += ' ORDER BY Name DESC LIMIT ' + info.recordToDisplay
                + ' OFFSET ' + (info.pageNumber - 1) * info.recordToDisplay;
        }
        
        return queryObjects;
    }
    
    @AuraEnabled
    //public static String unlinkOperation (String recordId, String idExplore){
    public static ObjectWrapper unlinkOperation(String infoJSON) {
        
        ComponentInfo info = (ComponentInfo)JSON.deserialize(infoJSON, ComponentInfo.class);
        
        String recordId = info.recordId;
        String idExplore = info.idExplore;
        
        //System.debug('# unlinkOperation / recordId : ' + recordId);
        //System.debug('# unlinkOperation / idExplore : ' + idExplore); 

		List<Operation__c> listOp = new List<Operation__c>();
        set<Id> opIds = new set<Id>();
        
        List<AnnonceOperations__c> lstAnnonceOperation = [SELECT Id, Operation__c, Annonce__c FROM AnnonceOperations__c WHERE Id =: recordId];
        //System.debug('# unlinkOperation / lstAnnonceOperation : ' + lstAnnonceOperation);
        
        for(AnnonceOperations__c ao : lstAnnonceOperation){
            opIds.add(ao.Operation__c);
        }
        
        listOp = [SELECT Id, Name, Compte__c, Compte__r.Name, Departement__c, estDansMonDepartement__c, estDansMonPole__c, 
                                            link__c,estDansMonService__c, estDansMonUFO__c, Nom_du_r_f_rent__c, Nombre_d_offres__c, Owner.FirstName, Owner.LastName  
                                            FROM Operation__c 
                                            WHERE Id IN :opIds];
        
        //System.debug('# unlinkOperation / listOp : ' + listOp.size());
        
        delete lstAnnonceOperation;

        return fetchData(infoJSON);
    }

    @AuraEnabled
    public static ObjectWrapper deleteRecord(String infoJSON) {
        ComponentInfo info = (ComponentInfo)JSON.deserialize(infoJSON, ComponentInfo.class);
        UserRecordAccess recAccess = [
            SELECT
            HasEditAccess,
            HasDeleteAccess,
            RecordId
            FROM UserRecordAccess
            WHERE UserId =: UserInfo.getUserId()
            AND RecordId =: info.recordId
        ];
        
        if (recAccess != null && recAccess.HasDeleteAccess) {
            try {
                sObject sObj = Schema.getGlobalDescribe().get(info.objectType).newSObject();
                sObj.Id = info.recordId;
                delete sObj;
            } catch (DmlException e) {
                throw new AuraHandledException('Error while deleting data.');
            }
        }
        
        return fetchData(infoJSON);
    }
    
    public class ObjectWrapper {
        @AuraEnabled public Integer pageSize {get;set;}
        @AuraEnabled public Integer page {get;set;}
        @AuraEnabled public Integer total {get;set;}
        @AuraEnabled public List<sObject> data {get;set;}
        
        ObjectWrapper(Integer pageSize, Integer page, Integer total, List<sObject> data) {
            this.pageSize = pageSize;
            this.page = page;
            this.total = total;
            this.data = data;
        }
        
        ObjectWrapper() {}
    }
    
    public class ComponentInfo {
        Integer pageNumber;
        Integer recordToDisplay;
        String objectType;
        String parentField;
        Id parentRecordId;
        Id recordId;
        String idExplore;
    }
}