force-app/main/default/objects/Annonce__c/Annonce__c.object-meta.xml
<CustomObject>
    <label>Annonce</label>
    <nameField>
        <label>Annonce</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Annonces</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Annonce__c/fields/Contenu__c.field-meta.xml
<CustomField>
    <fullName>Contenu__c</fullName>
    <label>Contenu</label>
    <length>70000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Annonce__c/fields/Objet__c.field-meta.xml
<CustomField>
    <fullName>Objet__c</fullName>
    <label>Objet</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AP08Veille_TEST.cls
/*
----------------------------------------------------------------------
-- - Name          : AP08Veille_TEST
-- - Author        : Boris THOMAS - Bluetis
-- - Description   : Test methods for AP08Veille
-- - Module        : CRM Ingerop
--
-- Maintenance History:
--
-- Date         Name  Version  Remarks  
-- -----------  ----  -------  ---------------------------------------
-- 27-SEP-2016   BTH    1.0      Initial version
----------------------------------------------------------------------
*/
@isTest
private class AP08Veille_TEST {
    static Annonce__c annonce;
    
    static{
        annonce = new Annonce__c();
        annonce.Objet__c = 'Test Annonce';
        annonce.Contenu__c = 'Contenu de mon annonce';
        
        insert annonce;
        
        Veille__c v = new Veille__c();
        v.Destinataire__c = UserInfo.getUserId();
        v.Annonce__c = annonce.Id;
        
        insert v;
    }
    static testMethod void testNoDuplicate(){
        
        Veille__c v2 = new Veille__c();
        v2.Destinataire__c = UserInfo.getUserId();
        v2.Annonce__c = annonce.Id;
        
        try{
            insert v2;
        } catch(DmlException e){
            String message = e.getMessage();
            System.assert(message.contains('Le destinataire de cette veille existe déjà pour cette annonce'), message);
        }
    }
}