force-app/main/default/objects/Annonce__c/Annonce__c.object-meta.xml
<CustomObject>
    <label>Annonce</label>
    <nameField>
        <label>Annonce</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Annonces</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Annonce__c/fields/Contenu__c.field-meta.xml
<CustomField>
    <fullName>Contenu__c</fullName>
    <label>Contenu</label>
    <length>70000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Annonce__c/fields/Objet__c.field-meta.xml
<CustomField>
    <fullName>Objet__c</fullName>
    <label>Objet</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Annonce__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Diffusée</fullName>
                <default>true</default>
                <label>Diffusée</label>
            </value>
            <value>
                <fullName>Prise en compte</fullName>
                <label>Affectée</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/VFC09PrendreVeille_TEST.cls
/*
----------------------------------------------------------------------
-- - Name          : VFC09PrendreVeille_TEST
-- - Author        : Boris THOMAS - Bluetis
-- - Description   : Test methods for VFC09PrendreVeille
-- - Module        : CRM Ingerop
--
-- Maintenance History:
--
-- Date         Name  Version  Remarks  
-- -----------  ----  -------  ---------------------------------------
-- 13-SEP-2016   BTH    1.0      Initial version
----------------------------------------------------------------------
*/
@isTest
private with sharing class VFC09PrendreVeille_TEST {
    static User utilisateur;
    static List<Annonce__c> listVeille;

    static{
        utilisateur = TestDataFactory.createTestUser(UserInfo.getProfileId(), 'Test', 'Test'); 
        insert utilisateur;

        System.runAs(utilisateur){
            listVeille = new List<Annonce__c>{
                new Annonce__c(Objet__c = 'Test Objet', Contenu__c = 'Contenu test')
            };
            insert listVeille;
        }
    }

    static testmethod void testRecuperer(){
        System.runAs(utilisateur){
            ApexPages.StandardController standardController = new ApexPages.StandardController(listVeille[0]);
            VFC09PrendreVeille controller = new VFC09PrendreVeille(standardController);
            VFC09PrendreVeille.recuperation(listVeille[0].Id);
            Annonce__c veille = DAL.getVeilleById(listVeille[0].Id);
            System.assertEquals(utilisateur.Id, veille.OwnerId);
            System.assertEquals('Prise en compte', veille.Statut__c);
        }   
    }
}