force-app/main/default/objects/Account/fields/Activite__c.field-meta.xml
<CustomField>
    <fullName>Activite__c</fullName>
    <inlineHelpText>Pour sélectionner plusieurs valeurs maintenez la touche Ctrl enfoncée</inlineHelpText>
    <label>Activité</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bâtiment</fullName>
            </value>
            <value>
                <fullName>Eau &amp; Environnement</fullName>
            </value>
            <value>
                <fullName>Énergie &amp; Industrie</fullName>
            </value>
            <value>
                <fullName>Ville &amp; Mobilité</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Prive_public__c.field-meta.xml
<CustomField>
    <fullName>Prive_public__c</fullName>
    <label>Privé/Public</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Public</fullName>
            </value>
            <value>
                <fullName>Privé</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/TECH_Activit_Batiment__c.field-meta.xml
<CustomField>
    <fullName>TECH_Activit_Batiment__c</fullName>
    <defaultValue>false</defaultValue>
    <label>TECH Activité Bâtiment</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/TECH_Activite_Eau_Environnement__c.field-meta.xml
<CustomField>
    <fullName>TECH_Activite_Eau_Environnement__c</fullName>
    <defaultValue>false</defaultValue>
    <label>TECH  Activité Eau &amp; Environnement</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/TECH_Activite_Energie_Industrie__c.field-meta.xml
<CustomField>
    <fullName>TECH_Activite_Energie_Industrie__c</fullName>
    <defaultValue>false</defaultValue>
    <label>TECH  Activité Energie &amp; Industrie</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/TECH_Activite_Ville_Mobilite__c.field-meta.xml
<CustomField>
    <fullName>TECH_Activite_Ville_Mobilite__c</fullName>
    <defaultValue>false</defaultValue>
    <label>TECH  Activité Ville &amp; Mobilité</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/AP10Compte_TEST.cls
/*
----------------------------------------------------------------------
-- - Name          : AP10Compte_TEST
-- - Author        : Boris THOMAS - Bluetis
-- - Description   : Test methods for class : AP10Compte
-- - Module        : CRM Ingerop
--
-- Maintenance History:
--
-- Date         Name  Version  Remarks  
-- -----------  ----  -------  ---------------------------------------
-- 10-NOV-2016   BTH    1.0      Initial version
----------------------------------------------------------------------
*/
@isTest
private class AP10Compte_TEST {
    static List<Account> listAccount;

    static{
        listAccount = new List<Account>{
            new Account(Name = 'Compte 1', Activite__c = Label.Batiment, Prive_public__c = 'Public'),
            new Account(Name = 'Compte 2', Activite__c = Label.Energie_Industrie, Prive_public__c = 'Public')
        };
        insert listAccount;
    }

    static testmethod void testModifyActivity(){
        listAccount[0].Activite__c = Label.Batiment+';'+Label.Eau_Environnement+';'+Label.Energie_Industrie+';'+Label.Ville_Mobilite;
        update listAccount[0];
        Account accountAfterUpdate = DAL.getAccountById(listAccount[0].Id);
        System.assert(accountAfterUpdate.TECH_Activit_Batiment__c);
        System.assert(accountAfterUpdate.TECH_Activite_Eau_Environnement__c);
        System.assert(accountAfterUpdate.TECH_Activite_Energie_Industrie__c);
        System.assert(accountAfterUpdate.TECH_Activite_Ville_Mobilite__c);
    }
}