force-app/main/default/objects/Account/fields/Activite__c.field-meta.xml
<CustomField>
    <fullName>Activite__c</fullName>
    <inlineHelpText>Pour sélectionner plusieurs valeurs maintenez la touche Ctrl enfoncée</inlineHelpText>
    <label>Activité</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bâtiment</fullName>
            </value>
            <value>
                <fullName>Eau &amp; Environnement</fullName>
            </value>
            <value>
                <fullName>Énergie &amp; Industrie</fullName>
            </value>
            <value>
                <fullName>Ville &amp; Mobilité</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Categorie__c.field-meta.xml
<CustomField>
    <fullName>Categorie__c</fullName>
    <label>Catégorie</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AMO, programmiste, MOD</fullName>
            </value>
            <value>
                <fullName>Architecte</fullName>
            </value>
            <value>
                <fullName>Autre</fullName>
            </value>
            <value>
                <fullName>Autre partenaire</fullName>
            </value>
            <value>
                <fullName>BE Spécialisé</fullName>
            </value>
            <value>
                <fullName>Conseils juridique, financier</fullName>
            </value>
            <value>
                <fullName>Exploitant</fullName>
            </value>
            <value>
                <fullName>Financeurs, Investisseurs, Crédit bailleurs</fullName>
            </value>
            <value>
                <fullName>Ingénierie</fullName>
            </value>
            <value>
                <fullName>Paysagiste</fullName>
            </value>
            <value>
                <fullName>Urbaniste</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Prive_public__c.field-meta.xml
<CustomField>
    <fullName>Prive_public__c</fullName>
    <label>Privé/Public</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Public</fullName>
            </value>
            <value>
                <fullName>Privé</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/SIRET__c.field-meta.xml
<CustomField>
    <fullName>SIRET__c</fullName>
    <description>Le numéro SIRET (Système Informatique pour le Répertoire des Entreprises sur le Territoire) est un identifiant composé de 14 chiffres attribué par l&apos;INSEE à chaque entreprise. Il se compose d&apos;une première série de chiffres qui correspond au numéro SIREN , la deuxième partie de quatre chiffres est appelée NIC (Numéro Interne de Classement). Dans ce système, une entreprise disposant de plusieurs établissements se voit attribuer plusieurs numéros SIRET.</description>
    <externalId>true</externalId>
    <label>SIRET</label>
    <length>14</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Annonce__c/Annonce__c.object-meta.xml
<CustomObject>
    <label>Annonce</label>
    <nameField>
        <label>Annonce</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Annonces</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Annonce__c/fields/Code_postal__c.field-meta.xml
<CustomField>
    <fullName>Code_postal__c</fullName>
    <label>Code postal</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Annonce__c/fields/Contenu__c.field-meta.xml
<CustomField>
    <fullName>Contenu__c</fullName>
    <label>Contenu</label>
    <length>70000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Annonce__c/fields/Date_d_echeance__c.field-meta.xml
<CustomField>
    <fullName>Date_d_echeance__c</fullName>
    <label>Date d&apos;échéance</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Annonce__c/fields/Date_de_parution__c.field-meta.xml
<CustomField>
    <fullName>Date_de_parution__c</fullName>
    <label>Date de parution</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Annonce__c/fields/IdExplore__c.field-meta.xml
<CustomField>
    <fullName>IdExplore__c</fullName>
    <externalId>true</externalId>
    <label>ID Explore</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Annonce__c/fields/IdExploreSimplifie__c.field-meta.xml
<CustomField>
    <fullName>IdExploreSimplifie__c</fullName>
    <description>ID Explore sans typage de marché</description>
    <label>ID Explore simplifie</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Annonce__c/fields/Lien_vers_l_annonce__c.field-meta.xml
<CustomField>
    <fullName>Lien_vers_l_annonce__c</fullName>
    <label>Lien vers l&apos;annonce</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Annonce__c/fields/Objet__c.field-meta.xml
<CustomField>
    <fullName>Objet__c</fullName>
    <label>Objet</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Annonce__c/fields/Operation__c.field-meta.xml
<CustomField>
    <fullName>Operation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opération</label>
    <referenceTo>Operation__c</referenceTo>
    <relationshipName>Veilles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Annonce__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Diffusée</fullName>
                <default>true</default>
                <label>Diffusée</label>
            </value>
            <value>
                <fullName>Prise en compte</fullName>
                <label>Affectée</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Annonce__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Appel d&apos;offre</fullName>
            </value>
            <value>
                <fullName>Appel à candidature</fullName>
            </value>
            <value>
                <fullName>Concours</fullName>
            </value>
            <value>
                <fullName>Conception réalisation</fullName>
            </value>
            <value>
                <fullName>CREM</fullName>
            </value>
            <value>
                <fullName>PPP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Annonce__c/fields/Ville__c.field-meta.xml
<CustomField>
    <fullName>Ville__c</fullName>
    <label>Ville</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AnnonceOperations__c/AnnonceOperations__c.object-meta.xml
<CustomObject>
    <description>Objet de lien entre Annonce et Opération</description>
    <label>Annonce Opération</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Annonce Opération</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Annonces / Opérations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AnnonceOperations__c/fields/Annonce__c.field-meta.xml
<CustomField>
    <fullName>Annonce__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Annonce</label>
    <referenceTo>Annonce__c</referenceTo>
    <relationshipLabel>Annonces / Opérations</relationshipLabel>
    <relationshipName>Annonce_Operation_Account</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AnnonceOperations__c/fields/Compte__c.field-meta.xml
<CustomField>
    <fullName>Compte__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compte</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Annonces / Opérations</relationshipLabel>
    <relationshipName>Annonces_Operations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AnnonceOperations__c/fields/Operation__c.field-meta.xml
<CustomField>
    <fullName>Operation__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opération</label>
    <referenceTo>Operation__c</referenceTo>
    <relationshipLabel>Annonces / Opérations</relationshipLabel>
    <relationshipName>Annonce_Operation_Account</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Operation__c/Operation__c.object-meta.xml
<CustomObject>
    <label>Opération</label>
    <nameField>
        <label>Nom de l&apos;opération</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opérations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Operation__c/fields/Activite__c.field-meta.xml
<CustomField>
    <fullName>Activite__c</fullName>
    <label>Activité</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bâtiment</fullName>
            </value>
            <value>
                <fullName>Eau &amp; Environnement</fullName>
            </value>
            <value>
                <fullName>Énergie &amp; Industrie</fullName>
            </value>
            <value>
                <fullName>Ville &amp; Mobilité</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Operation__c/fields/Code_postal__c.field-meta.xml
<CustomField>
    <fullName>Code_postal__c</fullName>
    <label>Code postal</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Operation__c/fields/Compte__c.field-meta.xml
<CustomField>
    <fullName>Compte__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Compte</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opérations</relationshipLabel>
    <relationshipName>Projets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Operation__c/fields/Departement__c.field-meta.xml
<CustomField>
    <fullName>Departement__c</fullName>
    <label>Département</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Pays__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1	Ain</fullName>
            </value>
            <value>
                <fullName>2	Aisne</fullName>
            </value>
            <value>
                <fullName>3	Allier</fullName>
            </value>
            <value>
                <fullName>4	Alpes de Haute Provence</fullName>
            </value>
            <value>
                <fullName>5	Hautes-Alpes</fullName>
            </value>
            <value>
                <fullName>6	Alpes-Maritimes</fullName>
            </value>
            <value>
                <fullName>7	Ardèche</fullName>
            </value>
            <value>
                <fullName>8	Ardennes</fullName>
            </value>
            <value>
                <fullName>9	Ariège</fullName>
            </value>
            <value>
                <fullName>10	Aube</fullName>
            </value>
            <value>
                <fullName>11	Aude</fullName>
            </value>
            <value>
                <fullName>12	Aveyron</fullName>
            </value>
            <value>
                <fullName>13	Bouches-du-Rhône</fullName>
            </value>
            <value>
                <fullName>14	Calvados</fullName>
            </value>
            <value>
                <fullName>15	Cantal</fullName>
            </value>
            <value>
                <fullName>16	Charente</fullName>
            </value>
            <value>
                <fullName>17	Charente-Maritime</fullName>
            </value>
            <value>
                <fullName>18	Cher</fullName>
            </value>
            <value>
                <fullName>19	Corrèze</fullName>
            </value>
            <value>
                <fullName>21	Côte d&apos;Or</fullName>
            </value>
            <value>
                <fullName>22	Côtes d&apos;Armor</fullName>
            </value>
            <value>
                <fullName>23	Creuse</fullName>
            </value>
            <value>
                <fullName>24	Dordogne</fullName>
            </value>
            <value>
                <fullName>25	Doubs</fullName>
            </value>
            <value>
                <fullName>26	Drôme</fullName>
            </value>
            <value>
                <fullName>27	Eure</fullName>
            </value>
            <value>
                <fullName>28	Eure-et-Loir</fullName>
            </value>
            <value>
                <fullName>29	Finistère</fullName>
            </value>
            <value>
                <fullName>2A	Corse du Sud</fullName>
            </value>
            <value>
                <fullName>2B	Haute Corse</fullName>
            </value>
            <value>
                <fullName>75	Paris</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Operation__c/fields/Objet__c.field-meta.xml
<CustomField>
    <fullName>Objet__c</fullName>
    <label>Objet</label>
    <length>13000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Operation__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>En cours</fullName>
                <default>true</default>
                <label>En cours</label>
            </value>
            <value>
                <fullName>Gagnée</fullName>
            </value>
            <value>
                <fullName>Perdue</fullName>
            </value>
            <value>
                <fullName>Abandonnée par le client</fullName>
            </value>
            <value>
                <fullName>Abandonnée par Ingérop</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Operation__c/fields/Ville__c.field-meta.xml
<CustomField>
    <fullName>Ville__c</fullName>
    <label>Ville</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LCCTRL_Explore_TEST.cls
/*
----------------------------------------------------------------------
-- - Name          : LCCTRL_Explore_TEST
-- - Author        : Sid Ramdowar
-- - Description   : Test methods for LCCTRL_Explore
-- - Module        : CRM Ingerop
--
-- Maintenance History:
--
-- Date         Name  Version  Remarks  
-- -----------  ----  -------  ---------------------------------------
-- 22-JUL-2019  SRA    1.0     Initial version
----------------------------------------------------------------------
*/

@isTest
Private class LCCTRL_Explore_TEST {
    
    static User user1;
    static List<Account> listCompte;
    static List<Operation__c> listOperation;
    static List<Annonce__c> listAnnonce;
    static List<AnnonceOperations__c> listAnnonceOperation;

    static{

        user1 = TestDataFactory.createTestUser(UserInfo.getProfileId(), 'Test', 'Test Code1');
        insert user1;

        System.runAs(user1){
            listCompte = new List<Account>{
                new Account(Name='Compte1', Activite__c='Ville & mobilité', Categorie__c='Architecte', Prive_public__c='Public', SIRET__c='123456789')
            };
            insert listCompte;

            listAnnonce = new List<Annonce__c>{
                new Annonce__c(Name = 'Annonce1', Contenu__c='Contenu annonce', Date_de_parution__c= date.today(), Date_d_echeance__c=date.today(), IdExplore__c='MP#1111111', Code_postal__c='06000', IdExploreSimplifie__c=1111111,Lien_vers_l_annonce__c='https://extranet.explore.fr/DotNet/AffichageMarchePublic.aspx?projet=1111111', Objet__c='Objet annonce',Statut__c='Diffusée', Type__c='Appel d\'offre', Ville__c='Nice'),
                new Annonce__c(Name = 'Annonce2', Contenu__c='Contenu annonce', Date_de_parution__c= date.today(), Date_d_echeance__c=date.today(), IdExplore__c='MP#2222222', Code_postal__c='06000', IdExploreSimplifie__c=2222222,Lien_vers_l_annonce__c='https://extranet.explore.fr/DotNet/AffichageMarchePublic.aspx?projet=2222222', Objet__c='Objet annonce',Statut__c='Diffusée', Type__c='Appel d\'offre', Ville__c='Paris'),
                new Annonce__c(Name = 'Annonce3', Contenu__c='Contenu annonce', Date_de_parution__c= date.today(), Date_d_echeance__c=date.today(), IdExplore__c='MP#3333333', Code_postal__c='06000', IdExploreSimplifie__c=3333333,Lien_vers_l_annonce__c='https://extranet.explore.fr/DotNet/AffichageMarchePublic.aspx?projet=3333333', Objet__c='Objet annonce',Statut__c='Diffusée', Type__c='Appel d\'offre', Ville__c='Paris'),
                new Annonce__c(Name = 'Annonce4', Contenu__c='Contenu annonce', Date_de_parution__c= date.today(), Date_d_echeance__c=date.today(), IdExplore__c='MP#4444444', Code_postal__c='06000', IdExploreSimplifie__c=4444444,Lien_vers_l_annonce__c='https://extranet.explore.fr/DotNet/AffichageMarchePublic.aspx?projet=4444444', Objet__c='Objet annonce',Statut__c='Diffusée', Type__c='Appel d\'offre', Ville__c='Paris')
            };
            insert listAnnonce;

            listOperation = new List<Operation__c>{
                new Operation__c(Name='Operation 1 - Annonce 1111111', Compte__c=listCompte[0].Id, Activite__c='Bâtiment', Code_postal__c='06000', Departement__c='6	Alpes-Maritimes', Objet__c='Objet operation', Pays__c='France', Phase_commerciale__c='Prospect', Privee_public__c='Public', Type_d_operation__c='Neuf',UFO__c='BUSINESS INGEROP CONTRACTING', Ville__c='NICE', Zone_geographique__c='Europe de l\'Ouest (zone "Euro")'),
                new Operation__c(Name='Operation 2 - Annonce 2222222', Compte__c=listCompte[0].Id, Activite__c='Bâtiment', Code_postal__c='75008', Departement__c='75	Paris', Objet__c='Objet operation', Pays__c='France', Phase_commerciale__c='Prospect', Privee_public__c='Public', Type_d_operation__c='Neuf',UFO__c='BUSINESS INGEROP CONTRACTING', Ville__c='PARIS', Zone_geographique__c='Europe de l\'Ouest (zone "Euro")'),
                new Operation__c(Name='Operation 3 - Annonce 3333333', Compte__c=listCompte[0].Id, Activite__c='Bâtiment', Code_postal__c='75008', Departement__c='75	Paris', Objet__c='Objet operation', Pays__c='France', Phase_commerciale__c='Prospect', Privee_public__c='Public', Type_d_operation__c='Neuf',UFO__c='BUSINESS INGEROP CONTRACTING', Ville__c='PARIS', Zone_geographique__c='Europe de l\'Ouest (zone "Euro")'),
                new Operation__c(Name='Operation 4 - Annonce 3333333', Compte__c=listCompte[0].Id, Activite__c='Bâtiment', Code_postal__c='75008', Departement__c='75	Paris', Objet__c='Objet operation', Pays__c='France', Phase_commerciale__c='Prospect', Privee_public__c='Public', Type_d_operation__c='Neuf',UFO__c='BUSINESS INGEROP CONTRACTING', Ville__c='PARIS', Zone_geographique__c='Europe de l\'Ouest (zone "Euro")'),
                new Operation__c(Name='Operation 5', Compte__c=listCompte[0].Id, Activite__c='Bâtiment', Code_postal__c='75008', Departement__c='75	Paris', Objet__c='Objet operation', Pays__c='France', Phase_commerciale__c='Prospect', Privee_public__c='Public', Type_d_operation__c='Neuf',UFO__c='BUSINESS INGEROP CONTRACTING', Ville__c='PARIS', Zone_geographique__c='Europe de l\'Ouest (zone "Euro")')
            };
            insert listOperation;
            
            listAnnonceOperation = new List<AnnonceOperations__c>{
                new AnnonceOperations__c(Annonce__c=listAnnonce[0].Id, Compte__c=listCompte[0].Id, Operation__c=listOperation[0].Id),
                new AnnonceOperations__c(Annonce__c=listAnnonce[1].Id, Compte__c=listCompte[0].Id, Operation__c=listOperation[1].Id),
                new AnnonceOperations__c(Annonce__c=listAnnonce[2].Id, Compte__c=listCompte[0].Id, Operation__c=listOperation[2].Id),
                new AnnonceOperations__c(Annonce__c=listAnnonce[2].Id, Compte__c=listCompte[0].Id, Operation__c=listOperation[3].Id)
            };
            insert listAnnonceOperation;
        }
    }
    
    static testMethod void testGetRelatedOperationsData(){
        System.runAs(user1){
            LCCTRL_Explore.getRelatedOperationsData('MP-3333333');
        }
    }
    
    static testMethod void testGetOtherOperationsData(){
        System.runAs(user1){
            LCCTRL_Explore.getOtherOperationsData('MP-1111111', listCompte[0].SIRET__c);
        }
    }
    
    static testMethod void testGetOperationsDataSearch(){
        System.runAs(user1){
            LCCTRL_Explore.getOperationsDataSearch('MP-3333333', 'Opé');
        }
    }
    
    static testMethod void testLinkAnnonceToOperation(){
        System.runAs(user1){

            Test.startTest();
            
			Test.setMock(HttpCalloutMock.class, new Explore_MockMarchePublic());
			String returnValue = LCCTRL_Explore.linkAnnonceToOperation(listOperation[4].Id, 'MP-5555555');
			String expectedValue = 'true';
			System.assertNotEquals(returnValue, null);

			Test.stopTest();
        }
    }

    static testMethod void testUnlinkOperation(){
        System.runAs(user1){
            LCCTRL_Explore.unlinkOperation(listOperation[0].Id, 'MP-1111111');
        }
    }

    static testMethod void testGetAnnonceMarchePublicData(){
        System.runAs(user1){

            Test.startTest();
            
			Test.setMock(HttpCalloutMock.class, new Explore_MockMarchePublic());
			String returnValue = LCCTRL_Explore.getAnnonceMarchePublicData('MP-1111111');
			System.assertNotEquals(returnValue, null);

			Test.stopTest();

        }
    }
    
    static testMethod void testGetAccountIdBySiret(){
        System.runAs(user1){
            LCCTRL_Explore.getAccountIdBySiret(listCompte[0].SIRET__c);
        }
    }

    static testMethod void testCreateAnnonce(){
        System.runAs(user1){
            
            Test.startTest();
            
			Test.setMock(HttpCalloutMock.class, new Explore_MockMarchePublic());
			String returnValue = LCCTRL_Explore.createAnnonce('MP-1111111');
			String expectedValue = 'true';
			System.assertNotEquals(returnValue, null);

			Test.stopTest();
        }
    }

    @IsTest(SeeAllData=true)
    static void testPostChatterFeedElement(){
        System.runAs(user1){
            List <Operation__c> lstOpe = [SELECT Id, Name, OwnerId FROM Operation__c ];
            Test.startTest();
            System.assertEquals(null, LCCTRL_Explore.postChatterFeedElement(listOperation[0].Id, 'Operation name', lstOpe[0].OwnerId, 'Object', listOperation[1].Id));
            Test.stopTest();
        }
    }

}