force-app/main/default/objects/Account/fields/Activite__c.field-meta.xml
<CustomField>
    <fullName>Activite__c</fullName>
    <inlineHelpText>Pour sélectionner plusieurs valeurs maintenez la touche Ctrl enfoncée</inlineHelpText>
    <label>Activité</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bâtiment</fullName>
            </value>
            <value>
                <fullName>Eau &amp; Environnement</fullName>
            </value>
            <value>
                <fullName>Énergie &amp; Industrie</fullName>
            </value>
            <value>
                <fullName>Ville &amp; Mobilité</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/TECH_Activit_Batiment__c.field-meta.xml
<CustomField>
    <fullName>TECH_Activit_Batiment__c</fullName>
    <defaultValue>false</defaultValue>
    <label>TECH Activité Bâtiment</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/TECH_Activite_Eau_Environnement__c.field-meta.xml
<CustomField>
    <fullName>TECH_Activite_Eau_Environnement__c</fullName>
    <defaultValue>false</defaultValue>
    <label>TECH  Activité Eau &amp; Environnement</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/TECH_Activite_Energie_Industrie__c.field-meta.xml
<CustomField>
    <fullName>TECH_Activite_Energie_Industrie__c</fullName>
    <defaultValue>false</defaultValue>
    <label>TECH  Activité Energie &amp; Industrie</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/TECH_Activite_Ville_Mobilite__c.field-meta.xml
<CustomField>
    <fullName>TECH_Activite_Ville_Mobilite__c</fullName>
    <defaultValue>false</defaultValue>
    <label>TECH  Activité Ville &amp; Mobilité</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/AP10Compte.cls
/*
----------------------------------------------------------------------
-- - Name          : AP10Compte
-- - Author        : Paul BENARD - Bluetis
-- - Description   : Methods for SObject Compte
-- - Module        : CRM Ingerop
--
-- Maintenance History:
--
-- Date         Name  Version  Remarks  
-- -----------  ----  -------  ---------------------------------------
-- 10-OCT-2016   PBE    1.0      Initial version
----------------------------------------------------------------------
*/
public class AP10Compte {
  public static void SetActivityTech(List<Account> listAccountNew,List<Account> listAccountOld){
      if(listAccountOld==null){
          for(Account a : listAccountNew){
            ModifyActivity(a);
          }
      }
      else{
          for(integer i = 0; i < listAccountNew.size(); i++){
            if(listAccountNew[i].Activite__c != listAccountOld[i].Activite__c){
                ModifyActivity(listAccountNew[i]);
            }
          }
      }
  }
    
    public static void ModifyActivity(Account a){
        if(a.Activite__c != null && (a.Activite__c).contains(Label.Batiment)){
            a.TECH_Activit_Batiment__c = true;
        }
        else{
            a.TECH_Activit_Batiment__c = false;
        }
        if(a.Activite__c != null && (a.Activite__c).contains(Label.Eau_Environnement)){
            a.TECH_Activite_Eau_Environnement__c = true;
        }
        else{
            a.TECH_Activite_Eau_Environnement__c = false;
        }
        if(a.Activite__c != null && (a.Activite__c).contains(Label.Energie_Industrie)){
            a.TECH_Activite_Energie_Industrie__c  = true;
        }
        else{
            a.TECH_Activite_Energie_Industrie__c = false;
        }
        if(a.Activite__c != null && (a.Activite__c).contains(Label.Ville_Mobilite)){
            a.TECH_Activite_Ville_Mobilite__c  = true;
        }
        else{
            a.TECH_Activite_Ville_Mobilite__c = false;
        }   
    } 
    
    
}