force-app/main/default/objects/Account/fields/Activite__c.field-meta.xml
<CustomField>
    <fullName>Activite__c</fullName>
    <inlineHelpText>Pour sélectionner plusieurs valeurs maintenez la touche Ctrl enfoncée</inlineHelpText>
    <label>Activité</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bâtiment</fullName>
            </value>
            <value>
                <fullName>Eau &amp; Environnement</fullName>
            </value>
            <value>
                <fullName>Énergie &amp; Industrie</fullName>
            </value>
            <value>
                <fullName>Ville &amp; Mobilité</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Categorie__c.field-meta.xml
<CustomField>
    <fullName>Categorie__c</fullName>
    <label>Catégorie</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AMO, programmiste, MOD</fullName>
            </value>
            <value>
                <fullName>Architecte</fullName>
            </value>
            <value>
                <fullName>Autre</fullName>
            </value>
            <value>
                <fullName>Autre partenaire</fullName>
            </value>
            <value>
                <fullName>BE Spécialisé</fullName>
            </value>
            <value>
                <fullName>Conseils juridique, financier</fullName>
            </value>
            <value>
                <fullName>Exploitant</fullName>
            </value>
            <value>
                <fullName>Financeurs, Investisseurs, Crédit bailleurs</fullName>
            </value>
            <value>
                <fullName>Ingénierie</fullName>
            </value>
            <value>
                <fullName>Paysagiste</fullName>
            </value>
            <value>
                <fullName>Urbaniste</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Prive_public__c.field-meta.xml
<CustomField>
    <fullName>Prive_public__c</fullName>
    <label>Privé/Public</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Public</fullName>
            </value>
            <value>
                <fullName>Privé</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Operation__c/Operation__c.object-meta.xml
<CustomObject>
    <label>Opération</label>
    <nameField>
        <label>Nom de l&apos;opération</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opérations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Operation__c/fields/Activite__c.field-meta.xml
<CustomField>
    <fullName>Activite__c</fullName>
    <label>Activité</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bâtiment</fullName>
            </value>
            <value>
                <fullName>Eau &amp; Environnement</fullName>
            </value>
            <value>
                <fullName>Énergie &amp; Industrie</fullName>
            </value>
            <value>
                <fullName>Ville &amp; Mobilité</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Operation__c/fields/Compte__c.field-meta.xml
<CustomField>
    <fullName>Compte__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Compte</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opérations</relationshipLabel>
    <relationshipName>Projets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AP04Operation_TEST.cls
/*
----------------------------------------------------------------------
-- - Name          : AP04Operation_TEST
-- - Author        : Boris THOMAS - Bluetis
-- - Description   : Test methods for AP04Operation
-- - Module        : CRM Ingerop
--
-- Maintenance History:
--
-- Date         Name  Version  Remarks  
-- -----------  ----  -------  ---------------------------------------
-- 17-JUN-2016   BTH    1.0      Initial version
-- 20-JUL-2018   NDI    2.0      Ouverture de droits
----------------------------------------------------------------------
*/
@isTest
private class AP04Operation_TEST {
    static User principalUser;
    static User user1;
    static User user2;
    static List<Account> listCompte;
    static List<Operation__c> listOperation;
    static List<Membre_du_compte__c> listMembreDuCompte;

    static{
        principalUser = TestDataFactory.createTestUser(UserInfo.getProfileId(), 'Test', 'Test');
        insert principalUser;

        user1 = TestDataFactory.createTestUser(UserInfo.getProfileId(), 'Test', 'Test Code1');
        insert user1;

        user2 = TestDataFactory.createTestUser(UserInfo.getProfileId(), 'Test', 'Test Code2');
        insert user2;

        System.runAs(principalUser){
            listCompte = new List<Account>{
                new Account(Name = 'Compte 1', Activite__c = 'Ville & mobilité', Categorie__c = 'Architecte', Prive_public__c = 'Public')
            };
            insert listCompte;

            listOperation = new List<Operation__c>{
                new Operation__c(Name = 'Test', Compte__c = listCompte[0].Id)
            };
            insert listOperation;

            listMembreDuCompte = new List<Membre_du_compte__c>{
                new Membre_du_compte__c(Utilisateur__c = user1.Id, Compte__c = listCompte[0].Id, Acces_a_operation__c = 'Lecteur'),
                new Membre_du_compte__c(Utilisateur__c = user2.Id, Compte__c = listCompte[0].Id, Acces_a_operation__c = 'Acteur/Lecteur')
            };
            insert listMembreDuCompte;
        }
    }

/*NDI20180720
    static testMethod void testCreateOperationShareOnAccount(){
        System.runAs(principalUser){
            AP04Operation.createOperationShareOnAccount(listOperation);
        }
        List<Operation__Share> listOperationShare = DAL.getOperationShareByOperationId(listOperation[0].Id);
        System.assertEquals(listMembreDuCompte.size(), listOperationShare.size());
    }
*/    
}