force-app/main/default/objects/Account/fields/Activite__c.field-meta.xml
<CustomField>
    <fullName>Activite__c</fullName>
    <inlineHelpText>Pour sélectionner plusieurs valeurs maintenez la touche Ctrl enfoncée</inlineHelpText>
    <label>Activité</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bâtiment</fullName>
            </value>
            <value>
                <fullName>Eau &amp; Environnement</fullName>
            </value>
            <value>
                <fullName>Énergie &amp; Industrie</fullName>
            </value>
            <value>
                <fullName>Ville &amp; Mobilité</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Categorie__c.field-meta.xml
<CustomField>
    <fullName>Categorie__c</fullName>
    <label>Catégorie</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AMO, programmiste, MOD</fullName>
            </value>
            <value>
                <fullName>Architecte</fullName>
            </value>
            <value>
                <fullName>Autre</fullName>
            </value>
            <value>
                <fullName>Autre partenaire</fullName>
            </value>
            <value>
                <fullName>BE Spécialisé</fullName>
            </value>
            <value>
                <fullName>Conseils juridique, financier</fullName>
            </value>
            <value>
                <fullName>Exploitant</fullName>
            </value>
            <value>
                <fullName>Financeurs, Investisseurs, Crédit bailleurs</fullName>
            </value>
            <value>
                <fullName>Ingénierie</fullName>
            </value>
            <value>
                <fullName>Paysagiste</fullName>
            </value>
            <value>
                <fullName>Urbaniste</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Prive_public__c.field-meta.xml
<CustomField>
    <fullName>Prive_public__c</fullName>
    <label>Privé/Public</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Public</fullName>
            </value>
            <value>
                <fullName>Privé</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Operation__c/Operation__c.object-meta.xml
<CustomObject>
    <label>Opération</label>
    <nameField>
        <label>Nom de l&apos;opération</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opérations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Operation__c/fields/Activite__c.field-meta.xml
<CustomField>
    <fullName>Activite__c</fullName>
    <label>Activité</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bâtiment</fullName>
            </value>
            <value>
                <fullName>Eau &amp; Environnement</fullName>
            </value>
            <value>
                <fullName>Énergie &amp; Industrie</fullName>
            </value>
            <value>
                <fullName>Ville &amp; Mobilité</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Operation__c/fields/Compte__c.field-meta.xml
<CustomField>
    <fullName>Compte__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Compte</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opérations</relationshipLabel>
    <relationshipName>Projets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Operation__c/fields/Phase_commerciale__c.field-meta.xml
<CustomField>
    <fullName>Phase_commerciale__c</fullName>
    <label>Phase commerciale</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prospect</fullName>
                <default>true</default>
                <label>Prospect</label>
            </value>
            <value>
                <fullName>Candidature</fullName>
            </value>
            <value>
                <fullName>Offre</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Operation__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>En cours</fullName>
                <default>true</default>
                <label>En cours</label>
            </value>
            <value>
                <fullName>Gagnée</fullName>
            </value>
            <value>
                <fullName>Perdue</fullName>
            </value>
            <value>
                <fullName>Abandonnée par le client</fullName>
            </value>
            <value>
                <fullName>Abandonnée par Ingérop</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AP07MembreDEquipeCandidature_TEST.cls
/*
----------------------------------------------------------------------
-- - Name          : AP07MembreDEquipeCandidature_TEST
-- - Author        : Boris THOMAS - Bluetis
-- - Description   : Test methods for AP07MembreDEquipeCandidature
-- - Module        : CRM Ingerop
--
-- Maintenance History:
--
-- Date         Name  Version  Remarks  
-- -----------  ----  -------  ---------------------------------------
-- 10-NOV-2016   BTH    1.0      Initial version
-- 08-JUL-2017   NDI    2.0      Statut candidature Perdue en Non retenue
----------------------------------------------------------------------
*/
@isTest
private class AP07MembreDEquipeCandidature_TEST {
    static List<Account> listAccount;
    static List<Operation__c> listOperation;
    static List<Equipe_Candidature__c> listEquipeCandidature;
    static List<Membre_d_Equipe_Candidature__c> listMembreDEquipeCandidature;

    static{
        listAccount = new List<Account>{
            new Account(Name = 'Compte 1', Activite__c = 'Bâtiment', Categorie__c = 'Architecte', Prive_public__c = 'Public'),
            new Account(Name = 'Compte 2', Activite__c = 'Bâtiment', Categorie__c = 'Architecte', Prive_public__c = 'Public'),
            new Account(Name = 'INGEROP', Activite__c = 'Bâtiment', Categorie__c = 'Architecte', Prive_public__c = 'Public')
        };
        insert listAccount;

        listOperation = new List<Operation__c>{
            new Operation__c(Name = 'test', Compte__c = listAccount[0].Id, Phase_commerciale__c = Label.PhaseCommerciale_Candidature)
        };
        insert listOperation;

        listEquipeCandidature = new List<Equipe_Candidature__c>{
            new Equipe_Candidature__c(Operation__c = listOperation[0].Id, Mandataire__c = listAccount[0].Id, Statut__c = Label.statut_nonRetenue, Date_limite_de_remise__c = Date.today()+3)
        };
        insert listEquipeCandidature;

        listMembreDEquipeCandidature = new List<Membre_d_Equipe_Candidature__c>{
            new Membre_d_Equipe_Candidature__c(Equipe_Candidature__c = listEquipeCandidature[0].Id, Compte__c = listAccount[0].Id, Mandataire__c = true),
            new Membre_d_Equipe_Candidature__c(Equipe_Candidature__c = listEquipeCandidature[0].Id, Compte__c = listAccount[1].Id)
        };
        insert listMembreDEquipeCandidature;
    }

    static testMethod void testUpdateMandataireToFalse(){
        listMembreDEquipeCandidature[0].Mandataire__c = false;
        update listMembreDEquipeCandidature[0];
        Equipe_Candidature__c ec = DAL.getEquipeCandidatureById(listEquipeCandidature[0].Id);
        System.assertEquals(null, ec.Mandataire__c);
    }

    static testMethod void testUpdateMandataireToTrue(){
        listMembreDEquipeCandidature[1].Mandataire__c = true;
        update listMembreDEquipeCandidature[1];
        Equipe_Candidature__c ec = DAL.getEquipeCandidatureById(listEquipeCandidature[0].Id);
        Membre_d_Equipe_Candidature__c mec = DAL.getMembreEquipeCandidatureById(listMembreDEquipeCandidature[0].Id);
        System.assertEquals(listAccount[1].Id, ec.Mandataire__c);
        System.assertEquals(false, mec.Mandataire__c);
    }

    static testMethod void testDeleteMandataire(){
        delete listMembreDEquipeCandidature[0];
        Equipe_Candidature__c ec = DAL.getEquipeCandidatureById(listEquipeCandidature[0].Id);
        System.assertEquals(null, ec.Mandataire__c);
    }
}