force-app/main/default/objects/Account/fields/Activite__c.field-meta.xml
<CustomField>
    <fullName>Activite__c</fullName>
    <inlineHelpText>Pour sélectionner plusieurs valeurs maintenez la touche Ctrl enfoncée</inlineHelpText>
    <label>Activité</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bâtiment</fullName>
            </value>
            <value>
                <fullName>Eau &amp; Environnement</fullName>
            </value>
            <value>
                <fullName>Énergie &amp; Industrie</fullName>
            </value>
            <value>
                <fullName>Ville &amp; Mobilité</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Categorie__c.field-meta.xml
<CustomField>
    <fullName>Categorie__c</fullName>
    <label>Catégorie</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AMO, programmiste, MOD</fullName>
            </value>
            <value>
                <fullName>Architecte</fullName>
            </value>
            <value>
                <fullName>Autre</fullName>
            </value>
            <value>
                <fullName>Autre partenaire</fullName>
            </value>
            <value>
                <fullName>BE Spécialisé</fullName>
            </value>
            <value>
                <fullName>Conseils juridique, financier</fullName>
            </value>
            <value>
                <fullName>Exploitant</fullName>
            </value>
            <value>
                <fullName>Financeurs, Investisseurs, Crédit bailleurs</fullName>
            </value>
            <value>
                <fullName>Ingénierie</fullName>
            </value>
            <value>
                <fullName>Paysagiste</fullName>
            </value>
            <value>
                <fullName>Urbaniste</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Prive_public__c.field-meta.xml
<CustomField>
    <fullName>Prive_public__c</fullName>
    <label>Privé/Public</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Public</fullName>
            </value>
            <value>
                <fullName>Privé</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Operation__c/Operation__c.object-meta.xml
<CustomObject>
    <label>Opération</label>
    <nameField>
        <label>Nom de l&apos;opération</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opérations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Operation__c/fields/Activite__c.field-meta.xml
<CustomField>
    <fullName>Activite__c</fullName>
    <label>Activité</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bâtiment</fullName>
            </value>
            <value>
                <fullName>Eau &amp; Environnement</fullName>
            </value>
            <value>
                <fullName>Énergie &amp; Industrie</fullName>
            </value>
            <value>
                <fullName>Ville &amp; Mobilité</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Operation__c/fields/Compte__c.field-meta.xml
<CustomField>
    <fullName>Compte__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Compte</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opérations</relationshipLabel>
    <relationshipName>Projets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Operation__c/fields/Date_previsionnelle_de_candidature__c.field-meta.xml
<CustomField>
    <fullName>Date_previsionnelle_de_candidature__c</fullName>
    <label>Date prévisionnelle de candidature</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Operation__c/fields/Phase_commerciale__c.field-meta.xml
<CustomField>
    <fullName>Phase_commerciale__c</fullName>
    <label>Phase commerciale</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prospect</fullName>
                <default>true</default>
                <label>Prospect</label>
            </value>
            <value>
                <fullName>Candidature</fullName>
            </value>
            <value>
                <fullName>Offre</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Operation__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>En cours</fullName>
                <default>true</default>
                <label>En cours</label>
            </value>
            <value>
                <fullName>Gagnée</fullName>
            </value>
            <value>
                <fullName>Perdue</fullName>
            </value>
            <value>
                <fullName>Abandonnée par le client</fullName>
            </value>
            <value>
                <fullName>Abandonnée par Ingérop</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AP02EquipeCandidature_TEST.cls
/*
----------------------------------------------------------------------
-- - Name          : AP02EquipeCandidature_TEST
-- - Author        : Boris THOMAS - Bluetis
-- - Description   : Test methods for AP02EquipeCandidature
-- - Module        : CRM Ingerop
--
-- Maintenance History:
--
-- Date         Name  Version  Remarks  
-- -----------  ----  -------  ---------------------------------------
-- 10-NOV-2016   BTH    1.0      Initial version
-- 09-JUL-2017	 NDI	2.0 	 Statut Candidature Perdue en Non Retenue
----------------------------------------------------------------------
*/
@isTest
private class AP02EquipeCandidature_TEST {
    static List<Account> listAccount;
    static List<Operation__c> listOperation;
    static List<Equipe_Candidature__c> listEquipeCandidature;

    static{
        listAccount = new List<Account>{
            new Account(Name = 'Compte 1', Activite__c = 'Bâtiment', Categorie__c = 'Architecte', Prive_public__c = 'Public'),
            new Account(Name = 'INGEROP', Activite__c = 'Bâtiment', Categorie__c = 'Architecte', Prive_public__c = 'Public')
        };
        insert listAccount;

        listOperation = new List<Operation__c>{
            new Operation__c(Name = 'test', Compte__c = listAccount[0].Id, Phase_commerciale__c = Label.PhaseCommerciale_Candidature),
            new Operation__c(Name = 'test2', Compte__c = listAccount[0].Id, Phase_commerciale__c = Label.PhaseCommerciale_Candidature, Date_previsionnelle_de_candidature__c = Date.today())
        };
        insert listOperation;

        listEquipeCandidature = new List<Equipe_Candidature__c>{
            //new Equipe_Candidature__c(Operation__c = listOperation[0].Id, Mandataire__c = listAccount[0].Id, Statut__c = Label.statut_Perdue, Date_limite_de_remise__c = Date.today()+3),
            //new Equipe_Candidature__c(Operation__c = listOperation[0].Id, Mandataire__c = listAccount[0].Id, Statut__c = Label.statut_Perdue),
            //NDI 20170708 : Perdue en Non Retenue
            new Equipe_Candidature__c(Operation__c = listOperation[0].Id, Mandataire__c = listAccount[0].Id, Statut__c = Label.statut_nonRetenue, Date_limite_de_remise__c = Date.today()+3),
            new Equipe_Candidature__c(Operation__c = listOperation[0].Id, Mandataire__c = listAccount[0].Id, Statut__c = Label.statut_nonRetenue),
            new Equipe_Candidature__c(Operation__c = listOperation[0].Id, Mandataire__c = listAccount[0].Id),
            new Equipe_Candidature__c(Operation__c = listOperation[1].Id, Mandataire__c = listAccount[0].Id)
        };
    }

    static testmethod void testCreateIngeropCoTraitant(){
        insert listEquipeCandidature;
        Equipe_Candidature__c ec = DAL.getEquipeCandidatureById(listEquipeCandidature[0].Id);
        List<Membre_d_Equipe_Candidature__c> listIngeropCoTraitant = DAL.getMembreEquipeCandidatureByEquipeCandidatureId(listEquipeCandidature[0].Id);
        System.assertEquals(listAccount[1].Id, ec.Mandataire__c);
        System.assertEquals(1, listIngeropCoTraitant.size());
    }

    static testmethod void testMajDateLimiteDeRemise(){
        insert listEquipeCandidature[3];
        Equipe_Candidature__c equipeDateNormale = DAL.getEquipeCandidatureById(listEquipeCandidature[3].Id);
        System.assertEquals(listOperation[1].Date_previsionnelle_de_candidature__c, equipeDateNormale.Date_limite_de_remise__c);
    }

    static testmethod void testMajOperationStatut(){
        insert listEquipeCandidature;
        //listEquipeCandidature[2].Statut__c = Label.statut_Perdue;
        //NDI 20170708 : Statut Candidature Perdue en Non Retenue
        listEquipeCandidature[2].Statut__c = Label.statut_nonRetenue;
        update listEquipeCandidature;
        Operation__c operation = DAL.getOperationById(listOperation[0].Id);
        System.assertEquals(Label.statut_Perdue, operation.Statut__c);
    }

    static testmethod void testEmptyMandataire(){
        insert listEquipeCandidature;
        AP02EquipeCandidature.emptyMandataireOnEquipe(new Map<Id, SObject>(listEquipeCandidature).keySet());
        Equipe_Candidature__c ec = DAL.getEquipeCandidatureById(listEquipeCandidature[0].Id);
        System.assertEquals(null, ec.Mandataire__c);
    }
}