force-app/main/default/objects/Account/fields/Alias__c.field-meta.xml
<CustomField>
    <fullName>Alias__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>si plusieurs alias, les séparer avec ;</inlineHelpText>
    <label>Alias</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/SIRET__c.field-meta.xml
<CustomField>
    <fullName>SIRET__c</fullName>
    <description>Le numéro SIRET (Système Informatique pour le Répertoire des Entreprises sur le Territoire) est un identifiant composé de 14 chiffres attribué par l&apos;INSEE à chaque entreprise. Il se compose d&apos;une première série de chiffres qui correspond au numéro SIREN , la deuxième partie de quatre chiffres est appelée NIC (Numéro Interne de Classement). Dans ce système, une entreprise disposant de plusieurs établissements se voit attribuer plusieurs numéros SIRET.</description>
    <externalId>true</externalId>
    <label>SIRET</label>
    <length>14</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Client.recordType-meta.xml
<RecordType>
    <fullName>Client</fullName>
    <active>true</active>
    <label>Client</label>
</RecordType>

force-app/main/default/classes/LCCTRL_ExploreAccountTest.cls
/**
 * @description       : This is a test class for LCCTRL_ExploreAccount controller class
 * @author            : subramanyam.jagadeesan@springfive.com
 * @group             : 
 * @last modified on  : 2023-05-30
 * @last modified by  : subramanyam.jagadeesan@springfive.com
**/

@isTest
public class LCCTRL_ExploreAccountTest {
    @isTest
    static void testExploreAccount(){
        Account acc = new Account(Name='Test Account', Alias__c = 'Test', SIRET__c = '40798530800011');
        insert acc;
        
        List<String> recordTypeList = LCCTRL_ExploreAccount.fetchRecordTypeValues();
        
        List<Account> searchAccounts = LCCTRL_ExploreAccount.getAccountsDataSearch('Test');
        System.assertEquals(1, searchAccounts.size());

        String accountId = LCCTRL_ExploreAccount.getAccountIdBySiret('40798530800011');
        System.assertEquals(acc.Id, accountId);
        System.assertEquals(null, LCCTRL_ExploreAccount.getAccountIdBySiret('40798530800012'));
        
        Test.startTest();
        LCCTRL_ExploreAccount.ExploreAccountWrapper accWrap = LCCTRL_ExploreAccount.createAccount('52504601700030', 'Client');
        System.assertEquals('0182462000', accWrap.Phone);
        Test.stopTest();

    }
}