force-app/main/default/objects/Account/fields/Moyenne_des_scores__c.field-meta.xml
<CustomField>
    <fullName>Moyenne_des_scores__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Moyenne des scores</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Note_attribuee__c.field-meta.xml
<CustomField>
    <fullName>Note_attribuee__c</fullName>
    <formula>IF(Moyenne_des_scores__c &gt;4.5,IMAGE(&quot;/resource/Stars/5_Star_Rating_System_5_stars_T.png&quot;, &quot;5&quot;, 15, 120), 
IF(Moyenne_des_scores__c &gt;4,IMAGE(&quot;/resource/Stars/5_Star_Rating_System_4_and_a_half_stars_T.png&quot;, &quot;4.5&quot;, 15, 120), 
IF(Moyenne_des_scores__c &gt;3.5,IMAGE(&quot;/resource/Stars/5_Star_Rating_System_4_stars_T.png&quot;, &quot;4&quot;, 15, 120), 
IF(Moyenne_des_scores__c &gt;3,IMAGE(&quot;/resource/Stars/5_Star_Rating_System_3_and_a_half_stars_T.png&quot;, &quot;3.5&quot;, 15, 120), 
IF(Moyenne_des_scores__c &gt;2.5,IMAGE(&quot;/resource/Stars/5_Star_Rating_System_3_stars_T.png&quot;, &quot;3&quot;, 15, 120), 
IF(Moyenne_des_scores__c &gt;2,IMAGE(&quot;/resource/Stars/5_Star_Rating_System_2_and_a_half_stars_T.png&quot;, &quot;2.5&quot;, 15, 120), 
IF(Moyenne_des_scores__c &gt;1.5,IMAGE(&quot;/resource/Stars/5_Star_Rating_System_2_stars_T.png&quot;, &quot;2&quot;, 15, 120), 
IF(Moyenne_des_scores__c &gt;1,IMAGE(&quot;/resource/Stars/5_Star_Rating_System_1_and_a_half_stars_T.png&quot;, &quot;1.5&quot;, 15, 120), 
IF(Moyenne_des_scores__c &gt;0.5,IMAGE(&quot;/resource/Stars/5_Star_Rating_System_1_star_T.png&quot;, &quot;1&quot;, 15, 120), 
IF(Moyenne_des_scores__c &gt;0,IMAGE(&quot;/resource/Stars/5_Star_Rating_System_0_and_half_star_T.png&quot;, &quot;0.5&quot;, 15, 120), 
IMAGE(&quot;/resource/Stars/5_Star_Rating_System_0_stars_T.png&quot;, &quot;0&quot;, 15, 120)))))))))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Note attribuée</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Partenaire.recordType-meta.xml
<RecordType>
    <fullName>Partenaire</fullName>
    <active>true</active>
    <label>Partenaire</label>
</RecordType>

force-app/main/default/classes/AP05Score.cls
/*
----------------------------------------------------------------------
-- - Name          : AP05Score
-- - Author        : Boris THOMAS - Bluetis
-- - Description   : Methods for SObject Score__c
-- - Module        : CRM Ingerop
--
-- Maintenance History:
--
-- Date         Name  Version  Remarks  
-- -----------  ----  -------  ---------------------------------------
-- 01-JUL-2016   BTH    1.0      Initial version
----------------------------------------------------------------------
*/
public without sharing class AP05Score {
	public static void majScorePartenaire(List<Score__c> listScore){
		Set<Id> partenaireIds = new Set<Id>();
		for(Score__c score : listScore){
			partenaireIds.add(score.Compte__c);
		}
		List<Score__c> listScorePartenaire = DAL.getNoteByAccountIds(partenaireIds);
		List<Account> listPartenaire = DAL.getAccountByIds(partenaireIds);
		for(Account partenaire : listPartenaire){
			List<Score__c> tempListScore = new List<Score__c>();
			partenaire.Moyenne_des_scores__c = 0;
			for(Score__c score : listScorePartenaire){
				if(score.Compte__c == partenaire.Id){
					tempListScore.add(score);
				}
			}
			if(tempListScore.size()>0){
				Decimal totalScore = 0;
				Integer nbScore = 0;
				for(Score__c score : tempListScore){
					totalScore += score.Note_attribuee__c;
					nbScore++;
				}
				if(nbScore>0){
					Decimal noteMoyenne = totalScore / nbScore;	
					partenaire.Moyenne_des_scores__c = noteMoyenne;				
				}
			}
		}
		update listPartenaire;
	}
}