force-app/main/default/objects/Operation__c/Operation__c.object-meta.xml
<CustomObject>
    <label>Opération</label>
    <nameField>
        <label>Nom de l&apos;opération</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opérations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Operation__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>En cours</fullName>
                <default>true</default>
                <label>En cours</label>
            </value>
            <value>
                <fullName>Gagnée</fullName>
            </value>
            <value>
                <fullName>Perdue</fullName>
            </value>
            <value>
                <fullName>Abandonnée par le client</fullName>
            </value>
            <value>
                <fullName>Abandonnée par Ingérop</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/VFC08SyncOffre.cls
/*
----------------------------------------------------------------------
-- - Name          : VFC08SyncOffre
-- - Author        : Boris THOMAS - Bluetis
-- - Description   : Extension for VFP08SyncOffre
-- - Module        : CRM Ingerop
--
-- Maintenance History:
--
-- Date         Name  Version  Remarks  
-- -----------  ----  -------  ---------------------------------------
-- 01-AUG-2016   BTH    1.0      Initial version
----------------------------------------------------------------------
*/
public with sharing class VFC08SyncOffre {
    public Offre__c offre {get;set;}
    public Operation__c operation;

    public VFC08SyncOffre(ApexPages.StandardController controller) {
        offre = DAL.getOffreById(controller.getRecord().Id);
        if(offre.Operation__c != null){
            operation = DAL.getOperationById(offre.Operation__c);
        }
    }

    public void synchroniser(){
        if(operation != null){
            if(offre.Statut__c == 'Gagnée'){
                operation.Statut__c = 'Traitée';
            }else if(offre.Statut__c == 'Perdue'){
                operation.Statut__c = 'Perdue';
            }else if(offre.Statut__c == 'Sans suite'){
                operation.Statut__c = 'Sans suite';
            }
            update operation;
        }   
    }
}