force-app/main/default/objects/Operation__c/Operation__c.object-meta.xml
<CustomObject>
    <label>Opération</label>
    <nameField>
        <label>Nom de l&apos;opération</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opérations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Operation__c/fields/Departement__c.field-meta.xml
<CustomField>
    <fullName>Departement__c</fullName>
    <label>Département</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Pays__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1	Ain</fullName>
            </value>
            <value>
                <fullName>2	Aisne</fullName>
            </value>
            <value>
                <fullName>3	Allier</fullName>
            </value>
            <value>
                <fullName>4	Alpes de Haute Provence</fullName>
            </value>
            <value>
                <fullName>5	Hautes-Alpes</fullName>
            </value>
            <value>
                <fullName>6	Alpes-Maritimes</fullName>
            </value>
            <value>
                <fullName>7	Ardèche</fullName>
            </value>
            <value>
                <fullName>8	Ardennes</fullName>
            </value>
            <value>
                <fullName>9	Ariège</fullName>
            </value>
            <value>
                <fullName>10	Aube</fullName>
            </value>
            <value>
                <fullName>11	Aude</fullName>
            </value>
            <value>
                <fullName>12	Aveyron</fullName>
            </value>
            <value>
                <fullName>13	Bouches-du-Rhône</fullName>
            </value>
            <value>
                <fullName>14	Calvados</fullName>
            </value>
            <value>
                <fullName>15	Cantal</fullName>
            </value>
            <value>
                <fullName>16	Charente</fullName>
            </value>
            <value>
                <fullName>17	Charente-Maritime</fullName>
            </value>
            <value>
                <fullName>18	Cher</fullName>
            </value>
            <value>
                <fullName>19	Corrèze</fullName>
            </value>
            <value>
                <fullName>21	Côte d&apos;Or</fullName>
            </value>
            <value>
                <fullName>22	Côtes d&apos;Armor</fullName>
            </value>
            <value>
                <fullName>23	Creuse</fullName>
            </value>
            <value>
                <fullName>24	Dordogne</fullName>
            </value>
            <value>
                <fullName>25	Doubs</fullName>
            </value>
            <value>
                <fullName>26	Drôme</fullName>
            </value>
            <value>
                <fullName>27	Eure</fullName>
            </value>
            <value>
                <fullName>28	Eure-et-Loir</fullName>
            </value>
            <value>
                <fullName>29	Finistère</fullName>
            </value>
            <value>
                <fullName>2A	Corse du Sud</fullName>
            </value>
            <value>
                <fullName>2B	Haute Corse</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Operation__c/fields/Departement_du_Pole__c.field-meta.xml
<CustomField>
    <fullName>Departement_du_Pole__c</fullName>
    <label>Département du Pôle</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Pole__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ACE-BI-Génie Energétique et Electrique</fullName>
            </value>
            <value>
                <fullName>ACE-BI-Management de Projets</fullName>
            </value>
            <value>
                <fullName>ACE-BI-Structures</fullName>
            </value>
            <value>
                <fullName>ACE-EM-DEFENSE MANUFACTURING &amp; SUPPORT</fullName>
            </value>
            <value>
                <fullName>ACE-EM-DEV &amp; OFFRES</fullName>
            </value>
            <value>
                <fullName>ACE-EM-DEVELOPPEMENT DIGITAL</fullName>
            </value>
            <value>
                <fullName>ACE-EM-ENERGIES NOUVELLES</fullName>
            </value>
            <value>
                <fullName>ACE-EM-GENIE CIVIL</fullName>
            </value>
            <value>
                <fullName>ACE-EM-NUCLEAIRE CIVIL</fullName>
            </value>
            <value>
                <fullName>ACE-EM-SYSTEMES</fullName>
                <isActive>false</isActive>
                <label>ACE-EM-SYSTEMES</label>
            </value>
            <value>
                <fullName>ACE-IVM-Infrastructures</fullName>
            </value>
            <value>
                <fullName>ACE-IVM-Ouvrages d&apos;Art</fullName>
            </value>
            <value>
                <fullName>ACE-IVM-Transports</fullName>
            </value>
            <value>
                <fullName>ACE-IVM-Ville</fullName>
            </value>
            <value>
                <fullName>BAE-ARA-Arcora</fullName>
            </value>
            <value>
                <fullName>BAE-BAE-BAE</fullName>
            </value>
            <value>
                <fullName>BAE-BAE-Conseil</fullName>
            </value>
            <value>
                <fullName>BAE-BAE-CVCD</fullName>
            </value>
            <value>
                <fullName>BAE-BAE-Electricité</fullName>
            </value>
            <value>
                <fullName>BAE-BAE-Privé</fullName>
            </value>
            <value>
                <fullName>BAE-BAE-Public et BIM</fullName>
            </value>
            <value>
                <fullName>BAE-BAE-Santé/Recherche/Enseignement supérieur/Export</fullName>
            </value>
            <value>
                <fullName>BAE-BAE-Structure et VRD</fullName>
            </value>
            <value>
                <fullName>BAE-CIC-Cicad</fullName>
            </value>
            <value>
                <fullName>GEOS</fullName>
            </value>
            <value>
                <fullName>GWT-BTZ-Biarritz</fullName>
            </value>
            <value>
                <fullName>GWT-BX-Bordeaux</fullName>
            </value>
            <value>
                <fullName>GWT-BX-Ville et Mobilité</fullName>
            </value>
            <value>
                <fullName>GWT-NA-Nantes</fullName>
            </value>
            <value>
                <fullName>GWT-RE-Rennes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Operation__c/fields/Pole__c.field-meta.xml
<CustomField>
    <fullName>Pole__c</fullName>
    <label>Pôle</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>UFO__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ACE-Bâtiment &amp; Industrie</fullName>
            </value>
            <value>
                <fullName>ACE-BU AMO</fullName>
                <isActive>false</isActive>
                <label>ACE-BU AMO</label>
            </value>
            <value>
                <fullName>ACE-BU Energie</fullName>
                <isActive>false</isActive>
                <label>ACE-BU Energie</label>
            </value>
            <value>
                <fullName>ACE-BU Génie Civil</fullName>
                <isActive>false</isActive>
                <label>ACE-BU Génie Civil</label>
            </value>
            <value>
                <fullName>ACE-BU Grands Projets</fullName>
                <isActive>false</isActive>
                <label>ACE-BU Grands Projets</label>
            </value>
            <value>
                <fullName>ACE-BU Nucléaire et Industrie</fullName>
                <isActive>false</isActive>
                <label>ACE-BU Nucléaire et Industrie</label>
            </value>
            <value>
                <fullName>ACE-BU Villes et Transports</fullName>
                <isActive>false</isActive>
                <label>ACE-BU Villes et Transports</label>
            </value>
            <value>
                <fullName>ACE-Energy &amp; Manufacturing 4.0</fullName>
            </value>
            <value>
                <fullName>ACE-Infrastructures Ville et Mobilité</fullName>
            </value>
            <value>
                <fullName>BAE-Arcora</fullName>
            </value>
            <value>
                <fullName>BAE-BAE</fullName>
            </value>
            <value>
                <fullName>BAE-Cicad</fullName>
            </value>
            <value>
                <fullName>GEOS</fullName>
            </value>
            <value>
                <fullName>GWT-Biarritz</fullName>
            </value>
            <value>
                <fullName>GWT-Bordeaux</fullName>
            </value>
            <value>
                <fullName>GWT-Nantes</fullName>
            </value>
            <value>
                <fullName>GWT-Rennes</fullName>
            </value>
            <value>
                <fullName>GWT-Toulouse</fullName>
            </value>
            <value>
                <fullName>ICO</fullName>
            </value>
            <value>
                <fullName>INT-Canada</fullName>
            </value>
            <value>
                <fullName>INT-Deutschland</fullName>
            </value>
            <value>
                <fullName>INT-East Africa</fullName>
            </value>
            <value>
                <fullName>INT-Geos Suisse</fullName>
            </value>
            <value>
                <fullName>INT-International</fullName>
            </value>
            <value>
                <fullName>INT-Rendel</fullName>
                <isActive>false</isActive>
                <label>INT-Rendel</label>
            </value>
            <value>
                <fullName>INT-South Africa</fullName>
            </value>
            <value>
                <fullName>INT-T3</fullName>
            </value>
            <value>
                <fullName>INT-West Africa</fullName>
            </value>
            <value>
                <fullName>IVT-AMO</fullName>
                <isActive>false</isActive>
                <label>IVT-AMO</label>
            </value>
            <value>
                <fullName>IVT-Infrastructures et Mobilités</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Operation__c/fields/UFO__c.field-meta.xml
<CustomField>
    <fullName>UFO__c</fullName>
    <label>UFO</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ALPES CENTRE EST</fullName>
            </value>
            <value>
                <fullName>BATIMENT &amp; EQUIPEMENTS</fullName>
            </value>
            <value>
                <fullName>BUSINESS INGEROP CONTRACTING</fullName>
            </value>
            <value>
                <fullName>GEOS</fullName>
            </value>
            <value>
                <fullName>GRAND OUEST</fullName>
            </value>
            <value>
                <fullName>INFRASTRUCTURES, VILLE &amp; TRANSPORTS</fullName>
            </value>
            <value>
                <fullName>INTERNATIONAL</fullName>
            </value>
            <value>
                <fullName>MEDITERRANEE</fullName>
            </value>
            <value>
                <fullName>NORD-EST</fullName>
            </value>
            <value>
                <fullName>RENDEL PLUS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AP09Repartition.cls
/*
----------------------------------------------------------------------
-- - Name          : AP09Repartition
-- - Author        : Paul BENARD - Bluetis
-- - Description   : Methods for SObject Repartition__c
-- - Module        : CRM Ingerop
--
-- Maintenance History:
--
-- Date         Name  Version  Remarks  
-- -----------  ----  -------  ---------------------------------------
-- 21-OCT-2016   ACU    1.0      Initial version
----------------------------------------------------------------------
*/
public class AP09Repartition {

    public static void createRepartition(Map<Id, Offre__c> mapOffreOld, List<Offre__c> listOffreNew){
        System.debug('## AP09Repartition.createRepartition START');
        List<Repartition__c> listRepartition = new List<Repartition__c>();
        Set<Id> offreIds = new Set<Id>();
        for(Offre__c offreNew : listOffreNew){
            if(offreNew.Operation__c != mapOffreOld.get(offreNew.Id).Operation__c){
                offreIds.add(offreNew.Id);
            }
        }
        if(offreIds.size()>0){
            List<Offre__c> listOffre = DAL.getOffreByIds(offreIds);
            for(Offre__c offre : listOffre){
                Repartition__c repartition = new Repartition__c();
                repartition.Offre__c = offre.Id;
                repartition.UFO__c = offre.Operation__r.UFO__c;
                repartition.Pole__c = offre.Operation__r.Pole__c;
                repartition.Departement__c = offre.Operation__r.Departement_du_pole__c;
                repartition.Service__c = offre.Operation__r.Service__c;
                repartition.Montant__c = offre.Montant_part_Ingerop__c == null ? 0 : offre.Montant_part_Ingerop__c;
                listRepartition.add(repartition);
            }
            if(listRepartition.size()>0){
                insert listRepartition;
            }
        }
        System.debug('## AP09Repartition.createRepartition END');
    }   
}