force-app/main/default/objects/CustomRecordComparaison__mdt/CustomRecordComparaison__mdt.object-meta.xml
<CustomObject>
    <label>CustomRecordComparaison</label>
    <pluralLabel>CustomRecordComparaisons</pluralLabel>
</CustomObject>

force-app/main/default/objects/CustomRecordComparaison__mdt/fields/MappedField__c.field-meta.xml
<CustomField>
    <fullName>MappedField__c</fullName>
    <label>Mapped Field</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomRecordComparaison__mdt/fields/SalesforceFieldAPIName__c.field-meta.xml
<CustomField>
    <fullName>SalesforceFieldAPIName__c</fullName>
    <label>Salesforce Field API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomRecordComparaison__mdt/fields/SalesforceObject__c.field-meta.xml
<CustomField>
    <fullName>SalesforceObject__c</fullName>
    <label>Salesforce Object</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomRecordComparaison__mdt/fields/ToBeCastedIn__c.field-meta.xml
<CustomField>
    <fullName>ToBeCastedIn__c</fullName>
    <label>To Be Casted In</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestDataFactoryTest.cls
@isTest
public class TestDataFactoryTest {

    @IsTest
    static void testGenerateTestCustomMetadataCastJSONToSObject() {
        Id profileId = [SELECT Id FROM Profile WHERE Name = 'System Administrator' OR Name = 'Administrateur Système' LIMIT 1].Id;
        TestDataFactory.createTestUser(profileId, 'TestFN', 'TestLN');
        TestDataFactory.TEST_returnEmpty = false;
        // Create test custom metadata records
        List<CustomRecordComparaison__mdt> lstCRC = TestDataFactory.generateTestCustomMetadataCastJSONToSObject();

        // Assert the field values
        System.assertEquals('Ext_Name', lstCRC[0].MappedField__c);
        System.assertEquals('String', lstCRC[0].ToBeCastedIn__c);
        System.assertEquals('AnnualRevenue', lstCRC[1].SalesforceFieldAPIName__c);
        System.assertEquals('Account', lstCRC[2].SalesforceObject__c);
    }
    
}